### ISSUE TITLE
Feature suggestion: Interactive, collapsible tree

### ISSUE THREAD

**Issue by DannyBen** [piotrmurach/tty-tree#1]
I think it would be great to combine the powers of TTY::Tree and TTY::Prompt to achieve a collapsible, interactive tree.

An example use case:
I have built a [CLI tool (as a gem)][1] for all the AudioAddict radio networks. One of its features, is to let you interactively browse the log of all your liked songs. Like this (right now, using TTY::Prompt menu option):

![out](https://user-images.githubusercontent.com/2405099/49885643-79d27d80-fe40-11e8-8b1d-5ea57b8ae2fa.gif)

[1]: https://github.com/DannyBen/audio_addict

**Comment by piotrmurach** [comment]
This is a great suggestion and I like it but I won't have any time to work on this given my long list of open source things to do. This could be a nice addition in `tty-prompt` if you have time to add it?

**Comment by DannyBen** [comment]
Yes it could. But as much as I would love to, it is unlikely I will have time to do it as I have my own gems to maintain :)

**Comment by piotrmurach** [comment]
Ok, so I'm going to close this ticket. There are many things that I want/need to work on in my OSS projects and this is not one of them. I also follow a new policy of keeping only tickets open that will be resolved. I believe that if other people want this feature it will surface in the future. Thanks for sharing your idea and happy hacking on your OSS stuff. 😄
